export const LOAD_INGREDIENTS = 'LOAD_INGREDIENTS'
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'


